# Generated by Django 2.2.6 on 2019-11-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_type', models.CharField(choices=[('ЭК', 'Эконом'), ('КМФ', 'Комфорт'), ('БИЗ', 'Бизнес'), ('ПКЛ', 'Первый класс')], default='', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'booking',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField(max_length=13, unique=True)),
                ('passport_series', models.CharField(max_length=2)),
                ('passport_number', models.CharField(max_length=7, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'passengers',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_model', models.CharField(default='AirBus A319', max_length=20, unique=True)),
                ('dep_time', models.TimeField()),
                ('arr_time', models.TimeField()),
                ('arr_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_plane', to='booking.City')),
                ('dep_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_plane', to='booking.City')),
            ],
            options={
                'verbose_name_plural': 'planes',
                'ordering': ['dep_station'],
            },
        ),
    ]
