# Generated by Django 2.2.6 on 2019-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191110_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='plane_num',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane_model',
            field=models.CharField(default='AirBus A319', max_length=20),
        ),
    ]
