# Generated by Django 2.2.6 on 2019-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191110_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='plane_num',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
