# Generated by Django 2.2.7 on 2019-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_plane_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='comfort_type',
            field=models.CharField(choices=[('Эконом', 'ЭК'), ('Комфорт', 'КМФ'), ('Бизнес', 'БИЗ'), ('Первый класс', 'ПКЛ')], default='', max_length=3),
        ),
    ]
