# Generated by Django 2.2.6 on 2019-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("booking", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="city", options={"ordering": ["name"], "verbose_name_plural": "cities"}
        ),
        migrations.AlterField(model_name="city", name="lat", field=models.FloatField()),
        migrations.AlterField(model_name="city", name="lon", field=models.FloatField()),
    ]
