# Generated by Django 2.2.6 on 2019-11-10 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_auto_20191110_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('flight_number', models.CharField(max_length=6, unique=True)),
                ('passenger_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.Passenger')),
                ('plane_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.Plane')),
            ],
            options={
                'verbose_name_plural': 'tickets',
                'ordering': ['pk'],
            },
        ),
    ]
